Subject: [PATCH] Makefile: Extraversion change
From: Guillaume Chopin <gchopin@student.42.fr>

EXTRAVERSION name updated

Signed-off-by: Guillaume Chopin <gchopin@student.42.fr>
---
diff --git a/Makefile b/Makefile
index 5a51eb52fcc4..62a519cdebdc 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@
 VERSION = 6
 PATCHLEVEL = 12
 SUBLEVEL = 0
-EXTRAVERSION = -rc2-gchopin
+EXTRAVERSION = -rc2-gchopin-thor_kernel
 NAME = Baby Opossum Posse
 
 # *DOCUMENTATION*
