Subject: [PATCH] Makefile: Extraversion change
From: Guillaume Chopin <gchopin@student.42.fr>

EXTRAVERSION name updated

Signed-off-by: Guillaume Chopin <gchopin@student.42.fr>
---
diff --git a/Makefile b/Makefile
index e6544066e70e..93ce21da9708 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@
 VERSION = 6
 PATCHLEVEL = 11
 SUBLEVEL = 0
-EXTRAVERSION = -rc5-gchopin
+EXTRAVERSION = -rc5-gchopin-thor_kernel
 NAME = Baby Opossum Posse
 
 # *DOCUMENTATION*
